= Keepon Reverse Engineering Document =

== Author Info

Kyle Machulis <kyle@nonpolynomial.com>
v1.0, Oct 31, 2011

== Updates ==

Keepoff is in heavy development, but mostly on the electronics side.
Most updates are currently posted to qDot's twitter account for the
time being.

http://www.twitter.com/qdot

== Description ==

Keepoff is a project to reverse engineer with BeatBots/WowToys
MyKeepon Dancing robot. 

http://mykeepon.com/

== Hardware ==

=== Sensors ===

* Microphone
* Buttons
* Servos (encoders?)

=== Processors and Components ===

* Padauk P234CS24 - http://www.jaolen.com/UploadFile/Content/2010091911223399.pdf
* Padauk P232CS14 - http://www.padauk.com.tw/admin/includes/getfile.php?file_name=ZmlsZTEuUDIzMl9EUzAyMUUucGRm
* APW7145 - http://www.lierda.com/upload/editor/20081212/1229063275.pdf

Pinouts:

P232CS14:
* PIN2 - I2C CLK
* PIN14 - I2C DATA

P234CS24:
* PIN11 - I2C CLK
* PIN24 - I2C DATA

=== Buttons ===

* Front (Touch/Music)
* Body (Head, Sides)

== Line Protocols ==

The two processors in the Keepon robot communicate with each other via
the I2C protocol. A set of pads to watch communication between the
chips is available on the circuit board, in the corner near the happy
face.

The communication is 0V (GND) Low, +3.3V High.

== Devices and Commands ==

The following device addresses are available:

* 0x52 - Sound bank access/playing
* 0x55 - Servos for turning whole unit?

=== Device Sleep ===

Assuming no interaction takes place for 3 minutes, the robot will put
itself to sleep. This will cause the data/clock lines on the I2C bus
to both drop to ground.

=== Device Wakeup ===

To wake up the device from sleep mode, pull the V line on the exposed
I2C pads to ground.

=== Servos ===

* Device Address: 0x55

Keepon has 4 servos: The main base rotation, right/left body bend,
forward/back body bend, and up/down "squat".

Messages written to the motors are as follows:

------
0x55 0xAA 0xBB 0xCC
------

* 0xAA - servo index. 
* 0xBB - current servo position
* 0xCC - unknown? Seems to be only 255 or single bit values (powers of 2)?

==== Main Rotation Base ====

* Motor Index: 0x04

==== Forward/Back Bend ====

* Motor Index: 0x02

==== Up/Down Squat ====

* Motor Index: 0x00

==== Right/Left Bend ====

* Motor Index: 0x06?

==== Motor Status? ====

A common communications event is to write a 0 to Device 0x55, then
read 12 bytes from it. Not really sure what these return bytes mean.
This happens about once every 14ms.

=== Sound Banks ===

* Device Index: 0x52
* Message Format: 0x52 0x01 0xAA
** 145 - Up Wakeup Sound
** 146 - Down Wakeup Sound
** 150 - Initial Boot Sound?
** 156 - Chirp
** 151 - Sigh
** 154 - Yawn Up
** 149 - Yawn Down
** 155 - Sleep
** 172 - Whine
** 189 - Up/Down noise when squatting
** 188 - Beep noise when head hit
** 191 - Sneeze Up
** 192 - Sneeze Down

=== Microphone ===

Unknown

=== Buttons - Front/Base ===

Unknown

=== Buttons - Robot Body ===

Unknown

